amp: true
bundle_root:
pretrained_path: 
ckpt_path: $@bundle_root + '/model_fold' + str(@fold)
data_file_base_dir: 
data_list_file_path: 
determ: false
finetune:
  activate: True
  pretrained_ckpt_name: $@pretrained_path + '/model_fold4' + '/best_metric_model.pt'
model_selection: Dice
fold: 0
infer:
  ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'
  data_list_key: testing
  fast: false
  ouptut_path: $@bundle_root + '/prediction_' + @infer#data_list_key
input_channels: 1
learning_rate: 0.0001
loss:
  _target_: DiceCELoss
  batch: true
  include_background: false
  sigmoid: $not @softmax
  smooth_dr: 1.0e-06
  smooth_nr: 0
  softmax: $@softmax
  squared_pred: true
  to_onehot_y: $@softmax
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.5
  optimizer: $@optimizer
  step_size: $@num_iterations // 5
num_images_per_batch: 8 # before 1
num_iterations: 20000
num_iterations_per_validation: 100
num_patches_per_image: 1
num_sw_batch_size: 8 # before 1
num_workers: 24 # before 8

optimizer:
  _target_: torch.optim.AdamW
  lr: '@learning_rate'
  weight_decay: 1.0e-05
output_classes: 2
overlap_ratio: 0.5
patch_size:
- 128
- 128
- 128
patch_size_valid:
- 128
- 128
- 128
softmax: true
validate:
  ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'
  ouptut_path: $@bundle_root + '/prediction_fold' + str(@fold)
  save_mask: true
