amp: true
bundle_root:
pretrained_path: 

ckpt_path: $@bundle_root + '/model'
data_file_base_dir: 
data_list_file_path: 
determ: true

finetune:
  activate: True
  pretrained_ckpt_name: $@pretrained_path + '/model' + '/best_metric_model.pt'

model_selection: Dice
fold: 0

infer:
  ckpt_name: $@bundle_root + '/model' + '/best_metric_model.pt'
  data_list_key: testing
  fast: false
  ouptut_path: $@bundle_root + '/prediction_' + @infer#data_list_key

input_channels: 1
learning_rate: 0.001

loss:
  _target_: DiceCELoss
  batch: true
  include_background: false
  sigmoid: $not @softmax
  smooth_dr: 1.0e-06
  smooth_nr: 0
  softmax: $@softmax
  squared_pred: true
  to_onehot_y: $@softmax

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.5
  optimizer: $@optimizer
  step_size: $@num_iterations // 5

num_images_per_batch: 2 # before 1
num_iterations: 1500
num_iterations_per_validation: 5
num_patches_per_image: 2 # before 1
num_sw_batch_size: 8 # before 1
num_workers: 12 # before 8
num_workers_val: 4

log_output_file: "$@bundle_root + '/model/training.log'"

optimizer:
  _target_: torch.optim.AdamW
  lr: '@learning_rate'
  weight_decay: 1.0e-05

output_classes: 2
overlap_ratio: 0.5

patch_size:
- 128
- 128
- 128

patch_size_valid:
- 128
- 128
- 128

softmax: true

validate:
  ckpt_name: $@bundle_root + '/model' + '/best_metric_model.pt'
  ouptut_path: $@bundle_root + '/prediction_fold' + str(@fold)
  save_mask: true
