_meta_: {}
network:
  _target_: SwinUNETR
  deep_supervision: false
  deep_supr_num: 1
  in_channels: $@training#input_channels
  kernel_size:
  - 3
  - [1, 1, 3]
  - 3
  - 3
  norm_name:
  - INSTANCE
  - {affine: true}
  out_channels: '@training#output_classes'
  res_block: false
  spatial_dims: 3
  strides: [1, 2, 2, 1]
  upsample_kernel_size: [2, 2, 1]
  num_res_units: 4
  channels: [16, 32, 64, 128, 256]
  strides: [2, 2, 2, 2]
  num_classes: 2