network:
  _target_: DynUnet
  spatial_dims: 3
  in_channels: $@input_channels
  out_channels: '@output_classes'
  kernel_size: [3, [1, 1, 3], 3, 3]
  strides: [1, 2, 2, 1]
  upsample_kernel_size: [2, 2, 1]
  norm_name: 
  - INSTANCE
  - {affine: True}
  deep_supervision: False
  deep_supr_num: 1
  res_block: False

  