_meta_: {}
network:
  _target_: UNet
  spatial_dims: 3
  in_channels: $@training#input_channels
  out_channels: '@training#output_classes'
  channels: [16, 32, 64, 128, 256]
  strides: [2, 2, 2, 2]
  kernel_size: 3
  up_kernel_size: 3
  num_res_units: 0
  norm: INSTANCE
  dropout: 0.0
  bias: True
  act: 'PRELU'
  adn_ordering: 'NDA'