_meta_: {}
image_key: image
label_key: label
transforms_train:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys: ['@image_key', '@label_key']
  - _target_: EnsureChannelFirstd
    keys: ['@image_key', '@label_key']
  - _target_: Orientationd
    axcodes: RAS
    keys: ['@image_key', '@label_key']
  - _target_: Spacingd
    align_corners: [true, true]
    keys: ['@image_key', '@label_key']
    mode: [bilinear, nearest]
    pixdim: [1.00000175362016, 0.9999999784513205, 0.9999999960636288]
  - {_target_: CastToTyped, dtype: $torch.float32, keys: '@image_key'}
  - {_target_: NormalizeIntensityd, channel_wise: true, keys: '@image_key', nonzero: true}
  - _target_: EnsureTyped
    keys: ['@image_key', '@label_key']
  - _target_: SpatialPadd
    keys: ['@image_key', '@label_key']
    mode: [reflect, constant]
    spatial_size: '@training#patch_size'
  - _target_: RandCropByLabelClassesd
    keys: ['@image_key', '@label_key']
    label_key: '@label_key'
    num_classes: '@training#output_classes'
    num_samples: '@training#num_patches_per_image'
    spatial_size: '@training#patch_size'
  - _target_: RandFlipd
    keys: ['@image_key', '@label_key']
    prob: 0.15
    spatial_axis: 0
  - _target_: RandFlipd
    keys: ['@image_key', '@label_key']
    prob: 0.15
    spatial_axis: 1
  - _target_: RandFlipd
    keys: ['@image_key', '@label_key']
    prob: 0.15
    spatial_axis: 2
  - _target_: RandRotated
    keys: ['@image_key', '@label_key']
    mode: [bilinear, nearest]
    prob: 0.15
    range_x: 0.3
    range_y: 0.3
    range_z: 0.0
  - {_target_: RandShiftIntensityd, keys: '@image_key', offsets: 0.1, prob: 0.15}
  - _target_: CastToTyped
    dtype: [$torch.float32, $torch.uint8]
    keys: ['@image_key', '@label_key']
