_meta_: {}
network:
  _target_: UNETR
  feature_size: 16                    # size of the feature maps in the network
  img_size: 128
  in_channels: $@training#input_channels
  out_channels: '@training#output_classes'
  # spatial_dims: 3
  hidden_size: 768                    # size of the hidden layers in the network
  mlp_dim: 3072                       # dimension of the multilayer perceptron (MLP) in the network
  num_heads: 12                       # number of heads in the multi-head attention mechanism of the network
  pos_embed: "perceptron"             # type of positional embedding
  norm_name: "instance"               # type of normalization
  res_block: True                     # indicates whether or not to use residual blocks in the network
  dropout_rate: 0.0                   # regularization technique that helps prevent overfitting
  # use_checkpoint: True
