---
bundle_root: null                                           # specify the root directory
ckpt_path: "$@bundle_root + '/model_fold' + str(@fold)"
data_file_base_dir: null                                    # specify the base directory for the data files
data_list_file_path: null                                   # specify the file path for the data list
fold: 0                                                     # fold number used for training, validation, and inference

training:
  # hyper-parameters
  amp: true                                                 # use Automatic Mixed Precision during training?
  determ: false                                             # training process should be deterministic or not
  input_channels: null
  learning_rate: 0.2
  num_images_per_batch: 2
  num_iterations: 40000
  num_iterations_per_validation: 500                        # number of iterations between each validation step during training
  num_patches_per_image: 1
  num_sw_batch_size: 2                                      # batch size for the sliding window during training
  output_classes: null
  overlap_ratio: 0.625
  patch_size: null
  patch_size_valid: null
  softmax: true                                             # apply softmax activation to the model's output during training?

  loss:
    _target_: DiceFocalLoss
    include_background: true
    to_onehot_y: "$@training#softmax"
    softmax: "$@training#softmax"
    sigmoid: "$not @training#softmax"
    squared_pred: true                                      # should predicted probabilities be squared during loss calculation?
    batch: true
    smooth_nr: 1.0e-05                                      # smoothing factor for the numerator in the loss calculation
    smooth_dr: 1.0e-05                                      # smoothing factor for the denominator in the loss calculation

  optimizer:
    _target_: torch.optim.SGD
    lr: "@training#learning_rate"
    momentum: 0.9
    weight_decay: 4.0e-05

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    optimizer: "$@training#optimizer"
    step_size: "$@training#num_iterations // 5"             # number of iterations before decreasing the learning rate
    gamma: 0.5                                              # multiplicative factor by which the learning rate is decreased

# fine-tuning
finetune:                                                   # fine-tuning is not activated
  activate: false
  pretrained_ckpt_name: "$@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'"

# validation
validate:
  ckpt_name: "$@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'"       # file path for the checkpoint model used for validation
  save_mask: true                                                                         # should predicted masks be saved?
  output_path: "$@bundle_root + '/prediction_fold' + str(@fold)"

# inference
infer:
  ckpt_name: "$@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'"       # file path for the checkpoint model used for inference
  fast: false                                                                             # inference should not be performed in fast mode
  data_list_key: testing                                                                  # testing data list should be used for inference
  output_path: "$@bundle_root + '/prediction_' + @infer#data_list_key"                    # represents the output path for the inference predictions
